engines/blorgh/config/routes.rb
Blorgh::Engine.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
end

engines/blorgh/app/models/blorgh/application_record.rb
module Blorgh
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/blorgh/app/models/blorgh/article.rb
module Blorgh
  class Article < ApplicationRecord
    has_many :comments
  end
end

engines/blorgh/app/models/blorgh/comment.rb
module Blorgh
  class Comment < ApplicationRecord
  end
end

engines/blorgh/app/controllers/blorgh/application_controller.rb
module Blorgh
  class ApplicationController < ActionController::Base
    # protect_from_forgery with: :exception
  end
end

engines/blorgh/app/controllers/blorgh/articles_controller.rb
require_dependency "blorgh/application_controller"

module Blorgh
  class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    # GET /articles
    def index
      @articles = Article.all
      render json: @articles
    end

    # GET /articles/1
    def show
      render json: @articles
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles
    def create
      @article = Article.new(article_params)

      if @article.save
        # redirect_to @article, notice: 'Article was successfully created.'
        render json: @article, status: :created, location: @article
      else
        render json: @article.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /articles/1
    def update
      if @article.update(article_params)
        render json: @article
      else
        render json: @article.errors, status: :unprocessable_entity
      end
    end

    # DELETE /articles/1
    def destroy
      @article.destroy
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def article_params
        params.require(:article).permit(:title, :text)
      end
  end
end

engines/blorgh/app/controllers/blorgh/comments_controller.rb
require_dependency "blorgh/application_controller"

module Blorgh
  class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      flash[:notice] = "Comment has been created!"
      redirect_to articles_path
    end

    private
      def comment_params
        params.require(:comment).permit(:text)
      end
  end
end

engines/blorgh/app/helpers/blorgh/application_helper.rb
module Blorgh
  module ApplicationHelper
  end
end

engines/blorgh/app/helpers/blorgh/articles_helper.rb
module Blorgh
  module ArticlesHelper
  end
end

engines/blorgh/app/helpers/blorgh/comments_helper.rb
module Blorgh
  module CommentsHelper
  end
end

engines/blorgh/app/views/blorgh4/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :article_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

engines/blorgh/app/views/blorgh4/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

engines/blorgh/app/views/blorgh4/articles/index.html.erb
<% if false %>
  <p id="notice"><%= notice %></p>
<% end %> <!--Sin comentarios...-->

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

engines/blorgh/app/views/blorgh4/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

engines/blorgh/app/views/blorgh4/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h3>Comments</h3>
<%= render @article.comments %>
<%= render "blorgh/comments/form" %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

engines/blorgh/app/views/blorgh4/comments/_comment.html.erb
<%= comment_counter + 1 %>. <%= comment.text %>

engines/blorgh/app/views/blorgh4/comments/_form.html.erb
<h3>New comment</h3>
<%= form_for [@article, @article.comments.build] do |f| %>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <%= f.submit %>
<% end %>

engines/blorgh/app/views/layouts/blorgh/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blorgh</title>
  <%= stylesheet_link_tag    "blorgh/application", media: "all" %>
  <%= javascript_include_tag "blorgh/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>